mrh0/createaddition

src/main/resources/assets/createaddition/lang/ru_ru.json

I have done a search-optimized and accurate translation for your mod.
Note: I translated Alternator as "Генератор" (Generator), as there is no special word for AC generator in Russian, and "Генератор переменного тока" (Alternating current generator) is a very long name.

Added Russian translation

---

src/main/resources/assets/createaddition/lang/zh_cn.json

Added Simplified Chinese Localization.

Added Simplified Chinese Localization.

---

src/main/resources/assets/createaddition/lang/es_es.json

Hi guys, how are you? I hope it's ok. I added full support for the Spanish language, I promise to be the maintainer of the language, greetings!

Added Spanish (es_es) language

---

src/main/resources/assets/createaddition/lang/zh_cn.json

Updated zh_cn.json

---

src/main/resources/assets/createaddition/lang/zh_cn.json

Standardized translations.

---

COMPUTERCRAFT.md

This adds syntax highlighting (Simply by adding a language to the codeblocks), and adds better Lua practices (Localizing all of the returned variables)
It also adds inline codeblocks to various functions, to make it look better.
It also has some grammatical fixes.

Add syntax highlighting, and locals to the documentation for ComputerCraft

---

src/main/java/com/mrh0/createaddition/blocks/accumulator/AccumulatorBlock.java
src/main/java/com/mrh0/createaddition/blocks/connector/ConnectorBlock.java

Fixes #238, #237, and partially #227.

Fixed connectors not working 

---

src/main/java/com/mrh0/createaddition/blocks/connector/ConnectorBlock.java
src/main/resources/assets/createaddition/models/block/accumulator/block.json
src/main/resources/assets/createaddition/models/block/alternator/block.json
src/main/resources/assets/createaddition/models/block/alternator/block_old.json
src/main/resources/assets/createaddition/models/block/alternator/item.json
src/main/resources/assets/createaddition/models/block/alternator/item_old.json
src/main/resources/assets/createaddition/models/block/brass_electric_motor.json
src/main/resources/assets/createaddition/models/block/charger/block.json
src/main/resources/assets/createaddition/models/block/connector/block.json
src/main/resources/assets/createaddition/models/block/creative_energy/block.json
src/main/resources/assets/createaddition/models/block/electric_motor.json
src/main/resources/assets/createaddition/models/block/electric_motor/block.json
src/main/resources/assets/createaddition/models/block/electric_motor/block_old.json
src/main/resources/assets/createaddition/models/block/electric_motor/item.json
src/main/resources/assets/createaddition/models/block/electric_motor/item_old.json
src/main/resources/assets/createaddition/models/block/heater/block.json
src/main/resources/assets/createaddition/models/block/redstone_relay/redstone_relay_off.json
src/main/resources/assets/createaddition/models/block/redstone_relay/redstone_relay_on.json
src/main/resources/assets/createaddition/models/block/rolling_mill/block.json
src/main/resources/assets/createaddition/models/block/rolling_mill/item.json
src/main/resources/assets/createaddition/models/block/tesla_coil/block.json
src/main/resources/assets/createaddition/models/block/tesla_coil/powered.json

Applied the same changes done on the Forge branch to the Fabric branch like in #247.

Better Connector placement + Optimised block models [Fabric]

---

build.gradle
gradle.properties
src/main/java/com/mrh0/createaddition/CreateAddition.java
src/main/java/com/mrh0/createaddition/compat/jei/CARecipeCategory.java
src/main/java/com/mrh0/createaddition/compat/jei/ChargingCategory.java
src/main/java/com/mrh0/createaddition/compat/jei/CreateAdditionJEI.java
src/main/java/com/mrh0/createaddition/compat/jei/RollingMillCategory.java
src/main/java/com/mrh0/createaddition/index/CABlocks.java
src/main/java/com/mrh0/createaddition/index/CAEntities.java
src/main/java/com/mrh0/createaddition/index/CAFluids.java
src/main/java/com/mrh0/createaddition/index/CAItems.java
src/main/java/com/mrh0/createaddition/index/CATileEntities.java
src/main/resources/META-INF/mods.toml
src/main/resources/assets/createaddition/lang/en_us.json

- Jar in Jar Registrate since Create no longer shadows it
- Refactor JEI categories to be similar to Create's
- Update build.gradle and mods.toml
- Update en_us.json to add iron_rod entry
- Current issues with this commit:
- runClient doesn't work but builds and runs fine outside of dev

Initial work for compatibility with Create 0.5d

---

src/main/java/com/mrh0/createaddition/index/CARecipes.java
src/main/java/com/mrh0/createaddition/recipe/rolling/RollingMillRecipeParams.java
src/main/java/com/mrh0/createaddition/recipe/rolling/RollingRecipe.java
src/main/java/com/mrh0/createaddition/recipe/rolling/RollingRecipeInfo.java
src/main/java/com/mrh0/createaddition/recipe/rolling/RollingRecipeProcessingFactory.java
src/main/java/com/mrh0/createaddition/recipe/rolling/SequencedAssemblyRollingRecipeSerializer.java

Well, here I am again.
Fixes a problem with recipe (de)serialization (replacing it, old class is still there) not extending from a create required class (no idea why that wasnt a problem the first time around), fixes a problem with the KubeJS Create integration for sequenced assembly.

Rolling Mill Sequenced Assembly - Serializer fix

---

build.gradle
gradle.properties

Reverts mrh0/createaddition#334

Revert "[FABRIC] Updated to 0.5d patch 2"

---

src/main/java/com/mrh0/createaddition/blocks/tesla_coil/TeslaCoilTileEntity.java

Found a fix for #305 
Solution was copying the old stack and changing the copy.

fix: fixes #305, tesla coil disappearing items

---

build.gradle

This fixes the dependency error in gradle, and (in my case) fixed the alternator crash bug 🎊

Fix incorrect link in dependencies

---

src/main/resources/data/createaddition/recipes/crushing/diamond.json

Fabric1.19.2 diamond grit fix

---

src/main/resources/data/createaddition/recipes/compat/immersiveengineering/electrum.json
src/main/resources/data/createaddition/recipes/compat/simplyjetpacks/thruster_ie1.json
src/main/resources/data/createaddition/recipes/compat/tconstruct/pig_iron.json
src/main/resources/data/createaddition/recipes/compat/tconstruct/queens_slime.json
src/main/resources/data/createaddition/recipes/compat/tconstruct/rose_gold.json
src/main/resources/data/createaddition/recipes/compat/tconstruct/slimesteel.json
src/main/resources/data/createaddition/recipes/crafting/capacitor_1.json
src/main/resources/data/createaddition/recipes/crafting/capacitor_2.json
src/main/resources/data/createaddition/recipes/crafting/rolling_mill.json
src/main/resources/data/createaddition/recipes/crafting/spool.json
src/main/resources/data/createaddition/recipes/mechanical_crafting/accumulator.json
src/main/resources/data/createaddition/recipes/mechanical_crafting/alternator.json
src/main/resources/data/createaddition/recipes/mechanical_crafting/electric_motor.json
src/main/resources/data/createaddition/recipes/mechanical_crafting/tesla_coil.json
src/main/resources/data/createaddition/recipes/pressing/zinc_ingot.json
src/main/resources/data/createaddition/recipes/rolling/brass_ingot.json
src/main/resources/data/createaddition/recipes/rolling/copper_plate.json
src/main/resources/data/createaddition/recipes/rolling/gold_ingot.json
src/main/resources/data/createaddition/recipes/rolling/gold_plate.json
src/main/resources/data/createaddition/recipes/rolling/iron_ingot.json
src/main/resources/data/createaddition/recipes/rolling/iron_plate.json

Updated crafting recipes to match new layout in create mod

[fabric][1.19.2] Crafting recipes broken due to changes in create mod

---

src/main/resources/data/createaddition/recipes/crafting/spool.json

nuggets also need to be changed
This is a supplement to https://github.com/mrh0/createaddition/pull/413.

fix spool craft recipes

---

src/main/resources/data/c/tags/fluids/plantoil.json

This recipes
https://github.com/mrh0/createaddition/blob/fabric-1.19.2/src/main/resources/data/createaddition/recipes/mixing/biomass_from_flowers.json
need thist tag.

Create plantoil tag

---

src/main/java/com/mrh0/createaddition/CreateAddition.java
src/main/java/com/mrh0/createaddition/compat/computercraft/PeripheralProvider.java

Adding this "PeripheralProvider" seemed to fix the electric motor not showing up as a peripheral. I'm not sure if the other stuff that was there is still needed.

Fix CC Compatibility

---

src/main/java/com/mrh0/createaddition/event/GameEvents.java

Make the blaze burner conversion common, rather than clientside

Fix straw usage being client-side only

---

gradle.properties

just a small version bump to ensure the code is compiled on the latest versions.

Fabric 1.18.2 version bump

---

gradle.properties

just a small version bump to ensure the code is compiled on the latest versions.

Fabric 1.19.2 version bump

---

src/main/java/com/mrh0/createaddition/blocks/portable_energy_interface/PortableEnergyInterfaceTileEntity.java
src/main/java/com/mrh0/createaddition/compat/computercraft/Peripherals.java
src/main/java/com/mrh0/createaddition/compat/computercraft/PortableEnergyInterfacePeripheral.java

Adds CC peripheral support to Portable Energy Interface, didn't know if you wanted this in the original PR so I did it here instead.

PEI Peripheral

---

src/main/java/com/mrh0/createaddition/blocks/redstone_relay/RedstoneRelay.java

[Fabric-1.18.2] Fix: relay ignoring redstone signal

---

COMPUTERCRAFT.md
COMPUTERCRAFT_zh-CN.md

I translated COMPUTERCRAFT.md into COMPUTERCRAFT_zh-CN.md (only motor currently) and corrented a slight error in the original version. You can check them anyway.
I am tend to finish the translation next Sunday. 
You need to sync manually, I think. I cannot deal with the so many branches of your project.
PS: I suggest you to create a folder to maintain the translated versions.

Translated COMPUTERCRAFT_zh-CN.md & corrected COMPUTERCRAFT.md

---

COMPUTERCRAFT.md
COMPUTERCRAFT_zh-CN.md

this is duplicated from the main branch.

Translation, correction and improvements of COMPUTERCRAFT.md

---

COMPUTERCRAFT.md
COMPUTERCRAFT_zh-CN.md

this is duplicated from the main branch.

Translations & Improvements to COMPUTERCRAFT.md

---

COMPUTERCRAFT_zh-CN.md

Corrected several mistakes and merged the changes in the original version, and translated them too.
Please Syncnorize them please. I don't have much time to create multiple pull requests today. And I think it is annoying too.
PS: The preview picture haven't been updated for years. I think you should update it. Just a suggestion.

Correction and update
